export const cadastroElements = {
    firstName:'#AccountFrm_firstname',
    lastName:'#AccountFrm_lastname',
    email:'#AccountFrm_email',
    telephone:'#AccountFrm_telephone',
    fax:'#AccountFrm_fax',
    company:'#AccountFrm_company',
    address1:'#AccountFrm_address_1',
    address2:'#AccountFrm_address_2',
    city:'#AccountFrm_city',
    zoneId:'#AccountFrm_zone_id',
    postcode:'#AccountFrm_postcode',
    countryId:'#AccountFrm_country_id',
    loginName:'#AccountFrm_loginname',
    password:'#AccountFrm_password',
    confirm:'#AccountFrm_confirm',
    newsletter:'#AccountFrm_newsletter0',
    agree:'#AccountFrm_agree',
    botaoSubmit:'.col-md-2 > .btn',
};